resources:

  Dbp\Relay\MonoBundle\ApiPlatform\Payment:
    types: [ 'https://schema.digital-blueprint.org/Payment' ]
    shortName: "MonoPayment"
    routePrefix: "/mono"
    normalizationContext:
      groups: [ "MonoPayment:output" ]
      jsonld_embed_context: true
    denormalizationContext:
      groups: [ "MonoPayment:input" ]
    operations:

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\MonoBundle\ApiPlatform\DummyProvider
        uriTemplate: "/payment"
        openapiContext:
          tags: ["ElectronicPayment"]

      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\MonoBundle\ApiPlatform\PaymentProvider
        uriTemplate: "/payment/{identifier}"
        openapiContext:
          tags: ["ElectronicPayment"]

      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\MonoBundle\ApiPlatform\PaymentProcessor
        uriTemplate: "/payment"
        openapiContext:
          tags: ["ElectronicPayment"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      type:
        iri: 'https://schema.org/Text'
      data:
        iri: "https://schema.org/Text"
      clientIp:
        iri: "https://schema.org/Text"
      returnUrl:
        iri: "https://schema.org/URL"
      notifyUrl:
        iri: "https://schema.org/URL"
      pspReturnUrl:
        iri: "https://schema.org/URL"
      localIdentifier:
        iri: "https://schema.org/Text"
      paymentStatus:
        iri: "https://schema.org/PaymentStatusType"
      paymentReference:
        iri: "https://schema.org/Text"
      amount:
        iri: "https://schema.org/Text"
      currency:
        iri: "https://schema.org/Text"
      alternateName:
        iri: "https://schema.org/Text"
      honorificPrefix:
        iri: "https://schema.org/Text"
      givenName:
        iri: "https://schema.org/Text"
      familyName:
        iri: "https://schema.org/Text"
      companyName:
        iri: "https://schema.org/Text"
      honorificSuffix:
        iri: "https://schema.org/Text"
      recipient:
        iri: "https://schema.org/Text"
      paymentMethod:
        iri: "https://schema.org/Text"
      dataProtectionDeclarationUrl:
        iri: "https://schema.org/URL"

  Dbp\Relay\MonoBundle\ApiPlatform\CompletePayAction:
    types: [ 'https://schema.digital-blueprint.org/CompletePayAction' ]
    shortName: "MonoCompletePayAction"
    routePrefix: "/mono"
    normalizationContext:
      groups: [ "MonoPayment:output" ]
      jsonld_embed_context: true
    denormalizationContext:
      groups: [ "MonoPayment:input" ]
    operations:

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\MonoBundle\ApiPlatform\DummyProvider
        uriTemplate: "/complete-pay-actions"
        openapiContext:
          tags: ["ElectronicPayment"]

      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\MonoBundle\ApiPlatform\DummyProvider
        uriTemplate: "/complete-pay-actions/{identifier}"
        openapiContext:
          tags: ["ElectronicPayment"]

      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\MonoBundle\ApiPlatform\CompletePayActionProcessor
        uriTemplate: "/complete-pay-actions"
        openapiContext:
          tags: ["ElectronicPayment"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      pspData:
        iri: 'https://schema.org/Text'
      returnUrl:
        iri: "https://schema.org/URL"

  Dbp\Relay\MonoBundle\ApiPlatform\StartPayAction:
    types: [ 'https://schema.digital-blueprint.org/StartPayAction' ]
    shortName: "MonoStartPayAction"
    routePrefix: "/mono"
    normalizationContext:
      groups: [ "MonoPayment:output" ]
      jsonld_embed_context: true
    denormalizationContext:
      groups: [ "MonoPayment:input" ]
    operations:

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\MonoBundle\ApiPlatform\DummyProvider
        uriTemplate: "/start-pay-actions"
        openapiContext:
          tags: ["ElectronicPayment"]

      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\MonoBundle\ApiPlatform\DummyProvider
        uriTemplate: "/start-pay-actions/{identifier}"
        openapiContext:
          tags: ["ElectronicPayment"]

      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\MonoBundle\ApiPlatform\StartPayActionProcessor
        uriTemplate: "/start-pay-actions"
        openapiContext:
          tags: ["ElectronicPayment"]

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      paymentMethod:
        iri: 'https://schema.org/Text'
      pspReturnUrl:
        iri: "https://schema.org/URL"
      consent:
        iri: "https://schema.org/Boolean"
      widgetUrl:
        iri: "https://schema.org/URL"
      pspData:
        iri: "https://schema.org/Text"
      pspError:
        iri: "https://schema.org/Text"
