services:
  Dbp\Relay\MonoBundle\Cron\CleanupCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Cron\NotifyCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Cron\NotifyErrorCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Cron\ReportingCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\BackendService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\PaymentService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_mono_bundle_entity_manager'
      $auditLogger: '@monolog.logger.dbp_relay_mono_audit'

  Dbp\Relay\MonoBundle\Service\ReportingService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_mono_bundle_entity_manager'

  Dbp\Relay\MonoBundle\Service\PaymentServiceProviderService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true
