services:
  Dbp\Relay\MonoBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\PaymentService:
    autowire: true
    autoconfigure: true
