services:
  Dbp\Relay\MonoBundle\Cron\CleanupCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Cron\NotifyCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Cron\NotifyErrorCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Reporting\ReportingCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Reporting\ReportingCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\ApiPlatform\:
    resource: '../../ApiPlatform'
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\BackendServiceProvider\BackendServiceRegistry:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Config\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\PaymentService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_mono_bundle_entity_manager'
      $auditLogger: '@monolog.logger.dbp_relay_mono_audit'

  Dbp\Relay\MonoBundle\Reporting\ReportingService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_mono_bundle_entity_manager'

  Dbp\Relay\MonoBundle\PaymentServiceProvider\PaymentServiceProviderServiceRegistry:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\CompletePaymentCommand:
    autowire: true
    autoconfigure: true
