services:
  Dbp\Relay\MonoBundle\Cron\CleanupCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Cron\NotifyCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Cron\NotifyErrorCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Cron\ReportingCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\BackendService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\PaymentService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoBundle\Service\PaymentServiceProviderService:
    autowire: true
    autoconfigure: true
